---
title: "Immune Mash V1 EZ eQTL Compare ALL"
author: "Yuxin Zou"
date: "12/3/2017"
output: html_document
---
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

# Set up data

```{r}
library(lattice)
library(ggplot2)
library(mashr)
load('../data/processed.RData')
gene.names.pro = processed.data$ctrl$V4
data = readRDS('../data/ImmuneQTLSummary.4MASH.rds')
data$max$se = data$max$beta/data$max$z
data$null$se = data$null$beta / data$null$z
gene.names.data = substr(row.names(data$max$beta),1,12)

K = 10
P = 5
vhat = 1
```

```{r}
if (vhat == 1) {
  V = cor(data$null$z[which(apply(abs(data$null$z),1, max) < 2),])
} else {
  V = diag(ncol(data$null$z))
}
mash_data = mashr::set_mash_data(Bhat = as.matrix(data$max$beta), 
                                 Shat = as.matrix(data$max$se), 
                                 V = as.matrix(V), 
                                 alpha = 1)
```

# MASH results

```{r}
# EZ
resEZ = readRDS('../output/ImmuneEZ.V1.center.mash_model.K10.P5.rds')
resEZ$result = readRDS('../output/ImmuneEZ.V1.center.mash_posterior.K10.P5.rds')
```

eQTL index in each group 

```{r}
eQTL.base = get_significant_results(resEZ, conditions=1)
eQTL.lps6h = get_significant_results(resEZ, conditions=2)
eQTL.lps90 = get_significant_results(resEZ, conditions=3)
eQTL.mdp6h = get_significant_results(resEZ, conditions=4)
eQTL.mdp90 = get_significant_results(resEZ, conditions=5)
eQTL.rna6h = get_significant_results(resEZ, conditions=6)
eQTL.rna90 = get_significant_results(resEZ, conditions=7)
```

eQTL index in the processed data

```{r}
eQTL.index = list(base=which(gene.names.pro %in% gene.names.data[eQTL.base]),
                  lps6h=which(gene.names.pro %in% gene.names.data[eQTL.lps6h]),
                  lps90=which(gene.names.pro %in% gene.names.data[eQTL.lps90]),
                  mdp6h=which(gene.names.pro %in% gene.names.data[eQTL.mdp6h]),
                  mdp90=which(gene.names.pro %in% gene.names.data[eQTL.mdp90]),
                  rna6h=which(gene.names.pro %in% gene.names.data[eQTL.rna6h]),
                  rna90=which(gene.names.pro %in% gene.names.data[eQTL.rna90]))
```

<!--
```{r}
gene.names.lps6h = substr(row.names(data$max$beta[eQTL.lps6h,]),1,12)
resEZ.lps6h = readRDS(paste0('../output/ImmuneEZ.V',vhat,'.center.resEZ.reQTL.lps6h.K',K,'.P',P,'.rds'))

gene.names.lps90 = substr(row.names(data$max$beta[eQTL.lps90,]),1,12)
resEZ.lps90 = readRDS(paste0('../output/ImmuneEZ.V',vhat,'.center.resEZ.reQTL.lps90.K',K,'.P',P,'.rds'))

gene.names.mdp6h = substr(row.names(data$max$beta[eQTL.mdp6h,]),1,12)
resEZ.mdp6h = readRDS(paste0('../output/ImmuneEZ.V',vhat,'.center.resEZ.reQTL.mdp6h.K',K,'.P',P,'.rds'))

gene.names.mdp90 = substr(row.names(data$max$beta[eQTL.mdp90,]),1,12)
resEZ.mdp90 = readRDS(paste0('../output/ImmuneEZ.V',vhat,'.center.resEZ.reQTL.mdp90.K',K,'.P',P,'.rds'))

gene.names.rna6h = substr(row.names(data$max$beta[eQTL.rna6h,]),1,12)
resEZ.rna6h = readRDS(paste0('../output/ImmuneEZ.V',vhat,'.center.resEZ.reQTL.rna6h.K',K,'.P',P,'.rds'))

gene.names.rna90 = substr(row.names(data$max$beta[eQTL.rna90,]),1,12)
resEZ.rna90 = readRDS(paste0('../output/ImmuneEZ.V',vhat,'.center.resEZ.reQTL.rna90.K',K,'.P',P,'.rds'))

reQTL.index = list(lps6h=which(gene.names.pro %in% gene.names.lps6h[get_significant_results(resEZ.lps6h)]),
                   lps90=which(gene.names.pro %in% gene.names.lps90[get_significant_results(resEZ.lps90)]),
                   mdp6h=which(gene.names.pro %in% gene.names.mdp6h[get_significant_results(resEZ.mdp6h)]),
                   mdp90=which(gene.names.pro %in% gene.names.mdp90[get_significant_results(resEZ.mdp90)]),
                   rna6h=which(gene.names.pro %in% gene.names.rna6h[get_significant_results(resEZ.rna6h)]),
                   rna90=which(gene.names.pro %in% gene.names.rna90[get_significant_results(resEZ.rna90)]))
```
-->

```{r}
logFC.compare = function(groupname){
  result = c()
  group = c()
  sti.data = processed.data[[groupname]]
  
  # eQTL base only
  n = length(eQTL.index$base)
  group = c(group, rep('eQTLBase', n))
  # base
  base.mean = apply(processed.data$ctrl[eQTL.index$base, 5:138],1 ,mean, na.rm=TRUE)
  # sti
  sti.mean = apply(sti.data[eQTL.index$base, 5:138],1 ,mean, na.rm=TRUE)
  
  result = c(result, log2(sti.mean/base.mean))

  # sti only
  n = length(eQTL.index[[groupname]])
  group = c(group, rep('eQTLSti', n))
  # base
  base.mean = apply(processed.data$ctrl[eQTL.index[[groupname]], 5:138],1 ,mean, na.rm=TRUE)
  # sti
  sti.mean = apply(sti.data[eQTL.index[[groupname]], 5:138],1 ,mean, na.rm=TRUE)
  
  result = c(result, log2(sti.mean/base.mean))
  
  # Both
  eQTLboth.index = Reduce(intersect, list(eQTL.index$base, eQTL.index[[groupname]]))
  n = length(eQTLboth.index)
  group = c(group, rep('eQTLBoth', n))
  # base
  base.mean = apply(processed.data$ctrl[eQTLboth.index, 5:138],1 ,mean, na.rm=TRUE)
  # sti
  sti.mean = apply(sti.data[eQTLboth.index, 5:138],1 ,mean, na.rm=TRUE)
  
  result = c(result, log2(sti.mean/base.mean))
  
  return(data.frame(logFC=result, group=factor(group, c('eQTLBoth', 'eQTLBase', 'eQTLSti'))))
}

```

# LPS 90
```{r}
lps90.logFC = logFC.compare('lps90')

g = ggplot(lps90.logFC, aes(x = group, y = logFC)) + geom_violin(trim = FALSE)
g = g + geom_boxplot(width=0.1)
g
```

# LPS 6h
```{r}
lps6h.logFC = logFC.compare('lps6h')

g = ggplot(lps6h.logFC, aes(x = group, y = logFC)) + geom_violin(trim = FALSE)
g = g + geom_boxplot(width=0.1)
g
```

# MDP 90
```{r}
mdp90.logFC = logFC.compare('mdp90')

g = ggplot(mdp90.logFC, aes(x = group, y = logFC)) + geom_violin(trim = FALSE)
g = g + geom_boxplot(width=0.1)
g
```

# MDP 6h
```{r}
mdp6h.logFC = logFC.compare('mdp6h')

g = ggplot(mdp6h.logFC, aes(x = group, y = logFC)) + geom_violin(trim = FALSE)
g = g + geom_boxplot(width=0.1)
g
```

# RNA 90
```{r}
rna90.logFC = logFC.compare('rna90')

g = ggplot(rna90.logFC, aes(x = group, y = logFC)) + geom_violin(trim = FALSE)
g = g + geom_boxplot(width=0.1)
g
```

# RNA 6h
```{r}
rna6h.logFC = logFC.compare('rna6h')

g = ggplot(rna6h.logFC, aes(x = group, y = logFC)) + geom_violin(trim = FALSE)
g = g + geom_boxplot(width=0.1)
g
```

# Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
