---
title: "Immune_Flash_MVN_Reduce"
author: "Yuxin Zou"
date: 2017-12-29
output: html_document
---

```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

```{r, echo=FALSE}
# TEMPORARY.
knitr::opts_chunk$set(eval = TRUE)
```

# Set up
```{r}
# Load required packages
library(mashr); library(ExtremeDeconvolution); library(flashr2); library(mclust)
FlashResult = readRDS('../output/Immune.flash2.center.greedy.K10.rds')
```

# Flash Loadings

From [Flash](Immune_Flash.html), we have $$\tilde{Z} = LF' + E$$
where F is $7 \times 5$, L is $n \times 5$, E is $n\times7$.

Suppose the rows of L come from a mixture of multivariate normals with covariances $U_{1}, \cdots, U_{n}$.
$$l_{i} \sim \sum_{m=1}^{n} \pi_{m} N_{5}(\mu_{m}, U_{m})$$
$$F l_{i} \sim \sum_{m=1}^{n} \pi_{m} N_{7}(F \mu_{m}, F U_{m}F')$$
```{r, eval=FALSE}
loading = FlashResult$L_flash[,1:5]
mod = Mclust(loading, G=1:50)
saveRDS(mod, '../output/Immune.flash.loading.reduce.rds')
```

```{r}
mod = readRDS('../output/Immune.flash.loading.reduce.rds')
summary(mod$BIC)
plot(mod, what = "BIC",legendArgs = list(x = "bottomleft"))
```

Using the model fitted above, we have 28 components.

$$l_{i} \sim \sum_{m=1}^{28} \hat{\pi}_{m} N_{5}(\hat{\mu}_{m}, \hat{U}_{m})$$

The estimated covariance structures for LF' are $F\hat{U}_{1}F', \cdots, F\hat{U}_{28}F'$.

```{r}
library(plyr)
U_list = alply(mod$parameters$variance$sigma,3)
Factors = FlashResult$F_flash[,1:5]
U_loading = lapply(U_list, function(U){Factors %*% (U %*% t(Factors))})
names(U_loading) = paste0('Load', "_", (1:length(U_loading)))
saveRDS(U_loading, '../output/Immune.flash.loading.reduce.cov.rds')
```

# Session information

<!-- Insert the session information into the document -->
```{r session-info}
```

